version: '3.9'
services:
  # should also build Nginx container with Certbot configured
  webserver_prod:
    image: nginx:latest
    profiles:
      - prod
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro

  graphql_engine_prod:
    image: 'docker.io/hasura/graphql-engine:latest'
    profiles:
      - prod
    env_file: .env
    depends_on:
      - webserver_prod
    container_name: graphql-engine
    ports:
    - "8080:8080"
    restart: unless-stopped
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://soundhealth:UrHjlLkLwbccHb5ukFt5@soundhealth-dev.cluster-cqni9kzmqmmb.us-east-1.rds.amazonaws.com:5432/sound_health
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false"
      HASURA_GRAPHQL_DEV_MODE: "true"
      ACTION_BASE_URL: https://services.dev.pointmotioncontrol.com
      HASURA_GRAPHQL_JWT_SECRET: '{"type":"HS256","key":"SgVkYp3s6v9y/B?E(H+MbQeThWmZq4t7ksadsakdj231312lkjlasdj12321JKHJJ"}'
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: guest
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: 8iPKaAmmeV7Ed
    command:
    - graphql-engine
    - serve

  sh_application_server_prod:
    build:
      context: .
      dockerfile: docker/Prod.Dockerfile
    profiles:
      - prod
    env_file: .env
    depends_on:
      - webserver_prod
      - graphql_engine_prod
    restart: unless-stopped
    ports:
      - 9000:9000

  sh_application_server_local:
    build:
      context: .
      dockerfile: docker/Local.Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    profiles:
      - local
    env_file: .env
    restart: unless-stopped
    ports:
      - 9000:9000
    # For hot reloading
    volumes:
      - ./:/usr/src/sh-application-server/local
      - ignore://usr/src/sh-application-server/local/node_modules
volumes:
  ignore:
