name: Push to EC2

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, dev, stage ]
  pull_request:
    branches: [ main, dev, stage ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set env to development
        if: endsWith(github.ref, '/dev')
        env:
          SSH_KEY: ${{ secrets.DEV_SSH_PRIVATE_KEY }}
        run: |
          echo "ENVIRONMENT=development" >> $GITHUB_ENV
          echo "SSH_REMOTE_PATH=/home/ubuntu/nestjs-app" >> $GITHUB_ENV
          echo "SSH_HOST=services.dev.pointmotioncontrol.com" >> $GITHUB_ENV
          echo "SSH_USER=ubuntu" >> $GITHUB_ENV
          echo SSH_PRIVATE_KEY=$(echo "${SSH_KEY}") >> $GITHUB_ENV

          echo ${{ secrets.DEV_SSH_PRIVATE_KEY_B64ENCODED }} | base64 -d >> ~/ssh_key.pem

      - name: Setup SSH Agent
        run: |
          chmod 400 ~/ssh_key.pem
          eval $(ssh-agent -s)
          ssh-add ~/ssh_key.pem
          #ssh-keyscan -t ed25519 $SSH_HOST >> ~/.ssh/known_hosts

      - uses: actions/checkout@v2
      - name: Setup upterm session
        uses: lhotari/action-upterm@v1

      - name: Build Deployable App
        run: |
         npm install
         npm run build

      - name: Copy Files Over Remote Server
        run: rsync -avzr --delete \
         /home/runner/work/sh-application-server/sh-application-server/node_modules \
         /home/runner/work/sh-application-server/sh-application-server/dist/ \
         $SSH_USER@$SSH_HOST:$SSH_REMOTE_PATH

      - name: Kill existing node processes and run the app.
        run: ssh $SSH_USER@$SSH_HOST "pkill -15 node; (. ~/.pmc-secrets;cd $SSH_REMOTE_PATH;nohup npx npm run start:prod >> /tmp/app-server.log 2>&1 &)"
